# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

#
# Build.ps1 downloads nuget.exe
#
- task: PowerShell@2
  displayName: Run Cake (Task="CIBUILD")
  inputs:
    targetType: filePath
    filePath: '.\build.ps1'
    arguments: '-Action CIBuild'  
    
  

# Publish Test Results to Azure Pipelines/TFS
- task: PublishTestResults@2
  displayName: Publish Unit Tests Results
  inputs:
    testResultsFormat: 'NUnit' # Options: JUnit, NUnit, VSTest, xUnit
    testResultsFiles: '**/Test*.xml' 
    #searchFolder: '$(System.DefaultWorkingDirectory)' # Optional
    #mergeTestResults: false # Optional
    #testRunTitle: # Optional
    #buildPlatform: # Optional
    #buildConfiguration: # Optional
    #publishRunAttachments: true # Optional

# - task: PowerShell@2
#   displayName: Run Pester
#   inputs:
#     targetType: filePath
#     filePath: '.\etc\demo.ps1'    

# - task: VSTest@2
#   inputs:
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'

## TODO deploy using MSDeploy

## Cypress.io tests

## Pester tests.
# This updates pester not always necessary but worth noting
# 1. URL exists
# 2. HTTP exists
# 3. HTTP redirect works
# 4. Certificate thumbprint
# 5. Expiration date


