# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

pool:
  vmImage: 'VS2017-Win2016'
  #name: myPrivateAgents
  #demands: agent.os -equals Windows_NT
  
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

#  
# Cake CIBuild
#
# Runs the following Cake Tasks
#     Build.ps1 downloads nuget.exe
#     Install nuget packages
#     (if on local machine, install build tools)
#     Clean
#     Front-end build
#     Build
#     Unit Tests
#     Publish
- task: PowerShell@2
  displayName: Run Cake (Task="CIBUILD")
  inputs:
    targetType: filePath
    filePath: '.\build.ps1'
    arguments: '-Action CIBuild'  

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '.\server\PrecompiledWeb' 
    artifactName: 'PrecompiledWeb' 
    #publishLocation: 'Container' # Options: container, filePath
    #targetPath: # Required when publishLocation == FilePath
    parallel: true # Optional
    #parallelCount: # Optional

- task: PublishTestResults@2
  displayName: Publish Unit Tests Results
  inputs:
    testResultsFormat: NUnit
    testResultsFiles: '**\TestResultsV2.xml' 
    #searchFolder: '$(System.DefaultWorkingDirectory)' # Optional
    mergeTestResults: false # Optional
    testRunTitle: # Optional
    buildPlatform: # Optional
    buildConfiguration: # Optional
    publishRunAttachments: true # Optional

# 
# Deploy
#
- task: PowerShell@2
  displayName: Deploy
  inputs:
    targetType: filePath
    filePath: '.\build.ps1'
    arguments: ' -Action Deploy -PublishSettings .\etc\kenticocicddemo.PublishSettings'    

# Publish Test Results to Azure Pipelines/TFS


# - task: PowerShell@2
#   displayName: Run Pester
#   inputs:
#     targetType: filePath
#     filePath: '.\etc\demo.ps1'    

# - task: VSTest@2
#   inputs:
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'

## TODO deploy using MSDeploy

## Cypress.io tests

## Pester tests.
# This updates pester not always necessary but worth noting
# 1. URL exists
# 2. HTTP exists
# 3. HTTP redirect works
# 4. Certificate thumbprint
# 5. Expiration date


