# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

pool:
  vmImage: 'VS2017-Win2016'
  #name: myPrivateAgents
  #demands: agent.os -equals Windows_NT
  
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:


#  
# Cake CIBuild
#
# Runs the following Cake Tasks
#     Build.ps1 downloads nuget.exe
#     Install nuget packages
#     (if on local machine, install build tools)
#     Clean
#     Front-end build (TODO)
#     Build
#     Unit Tests
#     Publish
- task: PowerShell@2
  displayName: Run Cake (Task="CIBUILD")
  inputs:
    targetType: filePath
    filePath: '.\build.ps1'
    arguments: '-Action CIBuild'  

#
# publisg unit and pester results
#
- task: PublishTestResults@2
  displayName: Publish Unit Tests Results
  inputs:
    testRunner: NUnit
    testResultsFiles: '**\*TestResults.xml'     


#
# Save artifcats
#
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '.\artifacts' 
    artifactName: 'PrecompiledWeb' 
    parallel: true


